import type { CarouselItem } from '../shared/carousel'
import demoCardUrl from './demo-card.png'

export const mockItems: CarouselItem[] = [
  {
    id: 1,
    title: 'Standard Item',
    imageUrl: demoCardUrl,
    description: 'A standard test item containing every supported carousel field.',
    tags: ['Alpha', 'Beta', 'Gamma'],
    destinationUrl: 'https://example.com/standard-item',
  },
  {
    id: 2,
    title: 'No Texture',
    imageUrl: null,
    description: 'This item verifies the textureless card fallback.',
    tags: ['Missing Image'],
    destinationUrl: 'https://example.com/no-texture',
  },
  {
    id: 3,
    title: 'No Destination',
    imageUrl: demoCardUrl,
    description: 'This item has no destination URL, so the Open action must not render.',
    tags: ['No Link'],
    destinationUrl: null,
  },
  {
    id: 4,
    title: 'No Tags',
    imageUrl: demoCardUrl,
    description: 'This item verifies that an empty tag list does not leave unwanted spacing.',
    tags: [],
    destinationUrl: 'https://example.com/no-tags',
  },
  {
    id: 5,
    title: 'Long Description',
    imageUrl: demoCardUrl,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tincidunt, velit sed consequat volutpat, urna sapien sollicitudin justo, vitae vulputate neque augue non nisl. Sed euismod, magna non feugiat malesuada, nibh erat posuere mauris, sed vulputate lectus lacus vitae enim. Suspendisse potenti. Curabitur tristique, sem quis aliquet tincidunt, sapien ipsum volutpat libero, non consequat lorem erat vel augue. Praesent feugiat, tortor at tincidunt consequat, neque justo facilisis mauris, sed malesuada nunc orci sed erat.',
    tags: ['Long Copy', 'Lorem Ipsum'],
    destinationUrl: 'https://example.com/long-description',
  },
  {
    id: 6,
    title: 'Empty Description',
    imageUrl: demoCardUrl,
    description: '',
    tags: ['No Description'],
    destinationUrl: 'https://example.com/empty-description',
  },
  {
    id: 7,
    title: 'A Deliberately Long Title For Responsive Layout Testing',
    imageUrl: demoCardUrl,
    description: 'This item verifies title wrapping in constrained layouts.',
    tags: ['Long Title'],
    destinationUrl: 'https://example.com/long-title',
  },
  {
    id: 8,
    title: 'Many Tags',
    imageUrl: demoCardUrl,
    description: 'This item verifies wrapping and separators across a large tag collection.',
    tags: [
      'One',
      'Two',
      'Three',
      'Four',
      'Five',
      'Six',
      'Seven',
      'Eight',
      'Nine',
      'Ten',
      'Eleven',
      'Twelve',
    ],
    destinationUrl: 'https://example.com/many-tags',
  },
  {
    id: 9,
    title: 'Minimal Item',
    imageUrl: null,
    description: '',
    tags: [],
    destinationUrl: null,
  },
]
